### ISSUE TITLE
merging to ZCU111-PYNQ?

### ISSUE THREAD

**Issue by yunqu** [Xilinx/SDFEC-PYNQ#3]
For this overlay folder, I am thinking about merging it to the ZCU111-PYNQ repo. I really don't see any reason why we keep many repositories lying in different places - I found this repo when looking into the ZCU111-PYNQ repo.

If SDFEC can support multiple boards, then it is perhaps better to keep this overlay folder separate, otherwise, it appears to be very difficult to track status of multiple repos and make them consistent.

**Comment by schelleg** [comment]
hi @yunqu - we'll keep it separate for now, but a good concern. 

SD-FEC IP does exist on several RFSoC parts (though the ZCU111 is still the only RFSoC **board** we support).  Keeping these repos separate is part of the same philosophy of keeping multi-board overlay repositories away from board repositories themselves.
